import "./globals.css";
import type { Metadata } from "next";
import { Inter, Jost } from "next/font/google";
import Nav from "./components/nav/nav";
import Home from "./page";
import SortingWorkflow from "./components/cv-sorting-workflow/sortingWorkflow";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CV-Soting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en ">
      <body className="no-scrollbar">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
